/**
 * 오류코드 카탈로그.
 *
 * 오류코드는 API 소비자와의 계약이다. 한 번 공개된 코드는 의미를 바꾸지 않는다.
 * 새 오류는 코드를 추가하고, 기존 코드의 의미를 재정의하지 않는다.
 *
 * 명명 규칙: `<도메인>_<사유>` 대문자 스네이크. 도메인 접두사는 생략 가능하다.
 */

export const ERROR_CODES = {
  // ── 공통 ─────────────────────────────────────────────────
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // ── 설정·환경 (T0-2, T0-3) ───────────────────────────────
  ENVIRONMENT_ERROR: 'ENVIRONMENT_ERROR',
  SETTING_LOCKED: 'SETTING_LOCKED',

  // ── 동시성 (R1a-2) ───────────────────────────────────────
  SERIALIZATION_FAILURE: 'SERIALIZATION_FAILURE',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // ── 승인 (T0-7 이후) ─────────────────────────────────────
  SELF_APPROVAL_FORBIDDEN: 'SELF_APPROVAL_FORBIDDEN',

  // ── SKU 도메인 (T1-2) ────────────────────────────────────
  SKU_CODE_IMMUTABLE: 'SKU_CODE_IMMUTABLE',
  SKU_ARCHIVE_BLOCKED: 'SKU_ARCHIVE_BLOCKED',

  // ── SKU CRUD (T1-3) ──────────────────────────────────────
  SKU_CODE_DUPLICATE: 'SKU_CODE_DUPLICATE',
  SKU_ACTIVE_UPDATE_RESTRICTED: 'SKU_ACTIVE_UPDATE_RESTRICTED',

  // ── SKU 승인 워크플로 (T1-4A) ────────────────────────────
  SKU_APPROVAL_VALIDATION_FAILED: 'SKU_APPROVAL_VALIDATION_FAILED',

  // ── SKU 코드 추천 (T03-7) ────────────────────────────────
  SKU_CODE_SEQUENCE_EXHAUSTED: 'SKU_CODE_SEQUENCE_EXHAUSTED',

  // ── 바코드 CRUD (T04-3, docs/10_설계복구_BarcodeCRUD.md) ──
  // ⚠️ `BARCODE_READ_AS_NUMBER` 는 여기 없다 — JSON API 는 Zod 가 문자열을
  //    강제하므로 그 분류는 공개 오류코드가 아니라 import/parser 전용
  //    도메인 결과값이다 (T04-2 `BarcodeErrorCode`).
  BARCODE_SCIENTIFIC_NOTATION: 'BARCODE_SCIENTIFIC_NOTATION',
  BARCODE_UNVERIFIED: 'BARCODE_UNVERIFIED',
  BARCODE_INVALID_FORMAT: 'BARCODE_INVALID_FORMAT',
  BARCODE_DUPLICATE: 'BARCODE_DUPLICATE',
  BARCODE_PRIMARY_CONFLICT: 'BARCODE_PRIMARY_CONFLICT',

  // ── 바코드 중복 예외 승인 (T04-4A, docs/11_설계복구_Barcode중복예외승인.md) ──
  BARCODE_DUPLICATE_EXCEPTION_NOT_APPLICABLE: 'BARCODE_DUPLICATE_EXCEPTION_NOT_APPLICABLE',
  BARCODE_DUPLICATE_CANDIDATE_EXISTS: 'BARCODE_DUPLICATE_CANDIDATE_EXISTS',
  BARCODE_DUPLICATE_APPROVAL_INVALID_STATE: 'BARCODE_DUPLICATE_APPROVAL_INVALID_STATE',
  BARCODE_DUPLICATE_APPROVAL_PENDING: 'BARCODE_DUPLICATE_APPROVAL_PENDING',

  // ── 외부 상품 매핑 CRUD (T05-2, docs/13_설계복구_외부상품매핑CRUD.md) ──
  EXTERNAL_MAPPING_CODE_DUPLICATE: 'EXTERNAL_MAPPING_CODE_DUPLICATE',
  EXTERNAL_MAPPING_PRIMARY_CONFLICT: 'EXTERNAL_MAPPING_PRIMARY_CONFLICT',
  EXTERNAL_MAPPING_IDENTIFIER_REQUIRED: 'EXTERNAL_MAPPING_IDENTIFIER_REQUIRED',
  EXTERNAL_MAPPING_PRIMARY_REQUIRES_MATCHED: 'EXTERNAL_MAPPING_PRIMARY_REQUIRES_MATCHED',
  EXTERNAL_MAPPING_PRIMARY_MUST_BE_CLEARED_BEFORE_END:
    'EXTERNAL_MAPPING_PRIMARY_MUST_BE_CLEARED_BEFORE_END',
  EXTERNAL_MAPPING_EFFECTIVE_DATE_INVALID: 'EXTERNAL_MAPPING_EFFECTIVE_DATE_INVALID',
  EXTERNAL_MAPPING_ENDED: 'EXTERNAL_MAPPING_ENDED',
  EXTERNAL_MAPPING_UNMATCHED_NOT_INTERACTIVE: 'EXTERNAL_MAPPING_UNMATCHED_NOT_INTERACTIVE',

  // ── 거래처·공급조건 API (T06-2, docs/17_설계복구_거래처공급조건.md §39~) ──
  SUPPLIER_CODE_DUPLICATE: 'SUPPLIER_CODE_DUPLICATE',
  SUPPLIER_SKU_PERIOD_OVERLAP: 'SUPPLIER_SKU_PERIOD_OVERLAP',
  SUPPLIER_SKU_EFFECTIVE_FROM_DUPLICATE: 'SUPPLIER_SKU_EFFECTIVE_FROM_DUPLICATE',
  SUPPLIER_SKU_PRIMARY_CONFLICT: 'SUPPLIER_SKU_PRIMARY_CONFLICT',
  SUPPLIER_SKU_EFFECTIVE_PERIOD_INVALID: 'SUPPLIER_SKU_EFFECTIVE_PERIOD_INVALID',
  SUPPLIER_SKU_VERSION_DATE_INVALID: 'SUPPLIER_SKU_VERSION_DATE_INVALID',

  // ── 가격이력 API (T06-3, docs/17_설계복구_거래처공급조건.md §58~) ──
  SUPPLIER_PRICE_EFFECTIVE_FROM_DUPLICATE: 'SUPPLIER_PRICE_EFFECTIVE_FROM_DUPLICATE',
  SUPPLIER_PRICE_UNIT_PRICE_INVALID: 'SUPPLIER_PRICE_UNIT_PRICE_INVALID',
  SUPPLIER_PRICE_CHAIN_CONFLICT: 'SUPPLIER_PRICE_CHAIN_CONFLICT',

  // ── BOM 도메인 (T07-2) ───────────────────────────────────
  // docs/18_설계복구_BOM.md §D-29 의 15종 중 **T07-2 도메인이 실제로 던지는
  // subset** 만 등록한다.
  BOM_NOT_FOUND: 'BOM_NOT_FOUND',
  BOM_CYCLE_DETECTED: 'BOM_CYCLE_DETECTED',
  BOM_MAX_LEVEL_EXCEEDED: 'BOM_MAX_LEVEL_EXCEEDED',
  BOM_EFFECTIVE_CONFLICT: 'BOM_EFFECTIVE_CONFLICT',
  /** ✏️ **T07-7A 가 활성화**했다 — D-23 대표 SupplierSku 가 2건 이상인 손상. */
  BOM_SUPPLIER_SELECTION_CONFLICT: 'BOM_SUPPLIER_SELECTION_CONFLICT',
  BOM_SELF_COMPONENT: 'BOM_SELF_COMPONENT',
  BOM_QTY_INVALID: 'BOM_QTY_INVALID',
  BOM_QTY_STATUS_MISMATCH: 'BOM_QTY_STATUS_MISMATCH',
  BOM_QTY_UNCONFIRMED: 'BOM_QTY_UNCONFIRMED',
  BOM_UOM_MISMATCH: 'BOM_UOM_MISMATCH',
  BOM_PARENT_NOT_ELIGIBLE: 'BOM_PARENT_NOT_ELIGIBLE',
  BOM_COMPONENT_NOT_ELIGIBLE: 'BOM_COMPONENT_NOT_ELIGIBLE',

  // ── BOM CRUD API (T07-3, docs/18 §D-29) ─────────────────
  // ✏️ `BOM_INVALID_TRANSITION` 은 **T07-5 가 활성화**했다 — D-6 전이표에 없는
  //    workflow 전이를 던진다. `BOM_SUPPLIER_SELECTION_CONFLICT` 는 **T07-7A 가
  //    활성화**했다 (D-23).
  BOM_INVALID_TRANSITION: 'BOM_INVALID_TRANSITION',
  BOM_ACTIVE_IMMUTABLE: 'BOM_ACTIVE_IMMUTABLE',
  BOM_NOT_EDITABLE: 'BOM_NOT_EDITABLE',
  BOM_VERSION_DUPLICATE: 'BOM_VERSION_DUPLICATE',
  BOM_PERIOD_OVERLAP: 'BOM_PERIOD_OVERLAP',
  BOM_LINE_DUPLICATE: 'BOM_LINE_DUPLICATE',

  // ── 창고 (T08-2, docs/19_설계복구_Warehouse.md) ──────────
  // ⛔ `WAREHOUSE_NOT_FOUND` 를 만들지 않는다 — 존재하지 않는 창고 참조는
  //    `productionPartnerNotFound` 선례대로 generic `NOT_FOUND`(404) 다.
  //    (`docs/06` 의 동명 코드는 **마이그레이션 DataIssue** 이며 runtime API
  //    error contract 가 아니다 — 혼동하지 말 것.)
  // ⛔ location 전용 duplicate code 도 만들지 않는다 (§W-D34 "새 error taxonomy
  //    금지") — `(warehouseId, locationCode)` 중복은 generic `CONFLICT`(409) 다.
  //    `common-code` 의 `duplicateCode()` 와 같은 방식이다.
  WAREHOUSE_CODE_DUPLICATE: 'WAREHOUSE_CODE_DUPLICATE',

  // ── 재고 (R1a-2, 설계 05 v0.2 §10.18) ────────────────────
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  REVERSAL_OF_REVERSAL_NOT_ALLOWED: 'REVERSAL_OF_REVERSAL_NOT_ALLOWED',
  ALREADY_REVERSED: 'ALREADY_REVERSED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  UNBALANCED_TRANSACTION: 'UNBALANCED_TRANSACTION',
  MISSING_SOURCE_DOCUMENT: 'MISSING_SOURCE_DOCUMENT',
  CLOSED_PERIOD_TRANSACTION: 'CLOSED_PERIOD_TRANSACTION',

  // ── Posting Phase-1 검증 (T2-5, 설계 05 v0.2 §8.2) ────────
  // ⛔ `SKU_NOT_FOUND` 를 만들지 않는다 — `docs/04 §8.2` ② 칸에 이름이 있으나
  //    `docs/05 §10.18` 카탈로그에 없고, §W-D34 가 `WAREHOUSE_NOT_FOUND` 전용
  //    코드를 거부한 선례가 있다. SKU·창고·로케이션 미존재는 전부 generic
  //    `NOT_FOUND`(404) 다.
  // ✏️ **T2-8 정정** — ⑦ 계열을 "8종" 으로 적었으나 T2-8 이 실제로 landing 하는
  //    것은 아래 **7종**이다. 나머지는 T2-8 소유가 아니다:
  //    ⛔ `INSUFFICIENT_SHELF_LIFE` — `docs/05 §10.18` 카탈로그에 **없고**,
  //       `04 v0.1 §8.5` 가 "(경고 또는 차단, **설정**)" 으로 적어 차단 여부·설정
  //       키가 확정되지 않았다. `minimumRemainingDays` 도 함께 유예한다.
  //    ⛔ `SERIAL_DUPLICATE` — "동일 `serialNo` 가 **이미 양수 잔량**" 은 현재고
  //       조회를 요구한다. T2-8 은 DB 접근 0 인 순수 도메인이라 판정할 수 없다.
  //       한 거래 **안의** 시리얼 중복은 `SERIAL_NET_QTY_INVALID` 가 잡는다.
  //    ⛔ `DIRECT_LOT_EDIT_FORBIDDEN` — 카탈로그가 소유를 **`조정`** 으로 명시한다
  //       (`TB-2`, R1b).
  //
  // `SKU_NOT_INVENTORY_MANAGED` 는 `docs/05 §10.18` 카탈로그가 이미 정의한
  // 코드이며(422, Posting ⑥), 여기 없던 것은 구현 gap 이었다.
  SKU_NOT_INVENTORY_MANAGED: 'SKU_NOT_INVENTORY_MANAGED',
  // `WAREHOUSE_INACTIVE` 는 `docs/04 §8.2` ② 의 검증 계약에 이름이 명시되어
  // 있다. "존재하지만 업무규칙상 쓸 수 없다" 이므로 404 도 400 도 아닌 422 다
  // (`SKU_ACTIVE_UPDATE_RESTRICTED` 와 같은 결). `Warehouse.active` 컬럼은
  // 실재하며, §W-D27 이 유예한 것은 mutation 이지 읽기가 아니다.
  WAREHOUSE_INACTIVE: 'WAREHOUSE_INACTIVE',

  // ── Posting ⑦ LOT·유통기한·시리얼 (T2-8, 설계 04 v0.2 §8.5 · 05 v0.2 §10.18) ──
  // 정확히 7종이다. 위 ✏️ 정정 주석이 제외 3종과 그 사유를 적었다.
  LOT_REQUIRED_MISSING: 'LOT_REQUIRED_MISSING',
  LOT_NOT_ALLOWED: 'LOT_NOT_ALLOWED',
  EXPIRY_REQUIRED_MISSING: 'EXPIRY_REQUIRED_MISSING',
  EXPIRED_INBOUND: 'EXPIRED_INBOUND',
  SERIAL_REQUIRED_MISSING: 'SERIAL_REQUIRED_MISSING',
  SERIAL_QTY_INVALID: 'SERIAL_QTY_INVALID',
  SERIAL_NET_QTY_INVALID: 'SERIAL_NET_QTY_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * 오류코드 → HTTP 상태.
 *
 * 카탈로그에 없는 코드는 500 으로 처리한다(안전한 기본값).
 */
const HTTP_STATUS_BY_CODE: Readonly<Record<ErrorCode, number>> = {
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.REAUTH_REQUIRED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.SELF_APPROVAL_FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.CONFLICT]: 409,
  [ERROR_CODES.SERIALIZATION_FAILURE]: 409,
  [ERROR_CODES.IDEMPOTENCY_KEY_REUSED]: 409,

  // 업무규칙 위반은 422. 요청 형식은 옳으나 도메인이 거부한 경우다.
  [ERROR_CODES.INSUFFICIENT_STOCK]: 422,
  [ERROR_CODES.REVERSAL_OF_REVERSAL_NOT_ALLOWED]: 422,
  [ERROR_CODES.ALREADY_REVERSED]: 422,
  [ERROR_CODES.INVALID_STATUS_TRANSITION]: 422,
  [ERROR_CODES.UNBALANCED_TRANSACTION]: 422,
  [ERROR_CODES.MISSING_SOURCE_DOCUMENT]: 422,
  [ERROR_CODES.CLOSED_PERIOD_TRANSACTION]: 422,
  [ERROR_CODES.SKU_NOT_INVENTORY_MANAGED]: 422,
  [ERROR_CODES.WAREHOUSE_INACTIVE]: 422,
  // Posting ⑦ (T2-8) — `docs/05 v0.2:351-354` 가 7종 전부 422 로 정한다.
  [ERROR_CODES.LOT_REQUIRED_MISSING]: 422,
  [ERROR_CODES.LOT_NOT_ALLOWED]: 422,
  [ERROR_CODES.EXPIRY_REQUIRED_MISSING]: 422,
  [ERROR_CODES.EXPIRED_INBOUND]: 422,
  [ERROR_CODES.SERIAL_REQUIRED_MISSING]: 422,
  [ERROR_CODES.SERIAL_QTY_INVALID]: 422,
  [ERROR_CODES.SERIAL_NET_QTY_INVALID]: 422,
  [ERROR_CODES.SETTING_LOCKED]: 422,
  [ERROR_CODES.SKU_CODE_IMMUTABLE]: 422,
  [ERROR_CODES.SKU_ARCHIVE_BLOCKED]: 422,
  [ERROR_CODES.SKU_CODE_DUPLICATE]: 409,
  [ERROR_CODES.SKU_ACTIVE_UPDATE_RESTRICTED]: 422,
  [ERROR_CODES.SKU_APPROVAL_VALIDATION_FAILED]: 422,
  [ERROR_CODES.SKU_CODE_SEQUENCE_EXHAUSTED]: 409,

  // 거래처·공급조건 (T06-2). 상태 충돌 3종은 409, 기간 semantics 위반은 422.
  [ERROR_CODES.SUPPLIER_CODE_DUPLICATE]: 409,
  [ERROR_CODES.SUPPLIER_SKU_PERIOD_OVERLAP]: 409,
  [ERROR_CODES.SUPPLIER_SKU_EFFECTIVE_FROM_DUPLICATE]: 409,
  [ERROR_CODES.SUPPLIER_SKU_PRIMARY_CONFLICT]: 409,
  [ERROR_CODES.SUPPLIER_SKU_EFFECTIVE_PERIOD_INVALID]: 422,
  [ERROR_CODES.SUPPLIER_SKU_VERSION_DATE_INVALID]: 422,

  // 가격이력 (T06-3). 동일 시작일·chain corruption 은 409, 금액 semantics 는 422.
  [ERROR_CODES.SUPPLIER_PRICE_EFFECTIVE_FROM_DUPLICATE]: 409,
  [ERROR_CODES.SUPPLIER_PRICE_UNIT_PRICE_INVALID]: 422,
  [ERROR_CODES.SUPPLIER_PRICE_CHAIN_CONFLICT]: 409,

  // 정규화 분류 실패는 요청 형식이 아니라 **업무규칙** 위반이다 → 422.
  [ERROR_CODES.BARCODE_SCIENTIFIC_NOTATION]: 422,
  [ERROR_CODES.BARCODE_UNVERIFIED]: 422,
  [ERROR_CODES.BARCODE_INVALID_FORMAT]: 422,
  // 조건부 UNIQUE 2종(T04-1) 위반은 상태 충돌 → 409.
  [ERROR_CODES.BARCODE_DUPLICATE]: 409,
  [ERROR_CODES.BARCODE_PRIMARY_CONFLICT]: 409,

  // 중복 예외 승인 (T04-4A). 상태·대상 판정 실패는 422, 후보 충돌은 409.
  [ERROR_CODES.BARCODE_DUPLICATE_EXCEPTION_NOT_APPLICABLE]: 422,
  [ERROR_CODES.BARCODE_DUPLICATE_CANDIDATE_EXISTS]: 409,
  [ERROR_CODES.BARCODE_DUPLICATE_APPROVAL_INVALID_STATE]: 422,
  [ERROR_CODES.BARCODE_DUPLICATE_APPROVAL_PENDING]: 422,

  // 외부 상품 매핑 (T05-2). 조건부 UNIQUE 2종 위반은 409, 업무규칙은 422.
  [ERROR_CODES.EXTERNAL_MAPPING_CODE_DUPLICATE]: 409,
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_CONFLICT]: 409,
  [ERROR_CODES.EXTERNAL_MAPPING_IDENTIFIER_REQUIRED]: 422,
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_REQUIRES_MATCHED]: 422,
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_MUST_BE_CLEARED_BEFORE_END]: 422,
  [ERROR_CODES.EXTERNAL_MAPPING_EFFECTIVE_DATE_INVALID]: 422,
  [ERROR_CODES.EXTERNAL_MAPPING_ENDED]: 422,
  [ERROR_CODES.EXTERNAL_MAPPING_UNMATCHED_NOT_INTERACTIVE]: 422,

  // BOM (T07-2). 데이터 손상은 409, 업무규칙 위반은 422 (docs/18 §D-29).
  [ERROR_CODES.BOM_NOT_FOUND]: 404,
  [ERROR_CODES.BOM_EFFECTIVE_CONFLICT]: 409,
  [ERROR_CODES.BOM_SUPPLIER_SELECTION_CONFLICT]: 409,
  [ERROR_CODES.BOM_CYCLE_DETECTED]: 422,
  [ERROR_CODES.BOM_MAX_LEVEL_EXCEEDED]: 422,
  [ERROR_CODES.BOM_SELF_COMPONENT]: 422,
  [ERROR_CODES.BOM_QTY_INVALID]: 422,
  [ERROR_CODES.BOM_QTY_STATUS_MISMATCH]: 422,
  [ERROR_CODES.BOM_QTY_UNCONFIRMED]: 422,
  [ERROR_CODES.BOM_UOM_MISMATCH]: 422,
  [ERROR_CODES.BOM_PARENT_NOT_ELIGIBLE]: 422,
  [ERROR_CODES.BOM_COMPONENT_NOT_ELIGIBLE]: 422,
  [ERROR_CODES.BOM_INVALID_TRANSITION]: 422,
  [ERROR_CODES.BOM_ACTIVE_IMMUTABLE]: 422,
  [ERROR_CODES.BOM_NOT_EDITABLE]: 422,
  [ERROR_CODES.BOM_VERSION_DUPLICATE]: 409,
  [ERROR_CODES.BOM_PERIOD_OVERLAP]: 409,
  [ERROR_CODES.BOM_LINE_DUPLICATE]: 409,

  // 창고 (T08-2). 중복 창고코드는 기존 `*_CODE_DUPLICATE` 계열과 같이 409 다.
  [ERROR_CODES.WAREHOUSE_CODE_DUPLICATE]: 409,

  [ERROR_CODES.ENVIRONMENT_ERROR]: 500,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
};

export const DEFAULT_HTTP_STATUS = 500;

export function httpStatusForCode(code: string): number {
  return HTTP_STATUS_BY_CODE[code as ErrorCode] ?? DEFAULT_HTTP_STATUS;
}

export function isKnownErrorCode(code: string): code is ErrorCode {
  return Object.prototype.hasOwnProperty.call(HTTP_STATUS_BY_CODE, code);
}

/**
 * 외부에 노출할 기본 메시지.
 *
 * 운영환경에서는 이 문장만 나간다. 내부 상세는 서버 로그에만 남는다.
 * 값·식별자·경로를 포함하지 않는다.
 */
const PUBLIC_MESSAGE_BY_CODE: Readonly<Record<ErrorCode, string>> = {
  [ERROR_CODES.VALIDATION_ERROR]: '요청 값이 올바르지 않습니다.',
  [ERROR_CODES.UNAUTHORIZED]: '로그인이 필요합니다.',
  [ERROR_CODES.REAUTH_REQUIRED]: '이 작업은 비밀번호 재확인이 필요합니다.',
  [ERROR_CODES.FORBIDDEN]: '이 작업을 수행할 권한이 없습니다.',
  [ERROR_CODES.SELF_APPROVAL_FORBIDDEN]: '작성자와 승인자는 달라야 합니다.',
  [ERROR_CODES.NOT_FOUND]: '요청한 대상을 찾을 수 없습니다.',
  [ERROR_CODES.CONFLICT]: '현재 상태에서는 처리할 수 없습니다.',
  [ERROR_CODES.SERIALIZATION_FAILURE]: '동시 요청이 충돌했습니다. 잠시 후 다시 시도하세요.',
  [ERROR_CODES.IDEMPOTENCY_KEY_REUSED]: '동일한 요청 키가 다른 내용으로 재사용되었습니다.',
  [ERROR_CODES.INSUFFICIENT_STOCK]: '재고가 부족합니다.',
  [ERROR_CODES.REVERSAL_OF_REVERSAL_NOT_ALLOWED]: '취소 거래는 다시 취소할 수 없습니다.',
  [ERROR_CODES.ALREADY_REVERSED]: '이미 취소된 거래입니다.',
  [ERROR_CODES.INVALID_STATUS_TRANSITION]: '허용되지 않은 상태 변경입니다.',
  // ⚠️ "증감 합계"라는 표현을 쓰지 않는다. 조립·분해(kit assemble/disassemble)는
  //    자재 감소와 완제품 증가의 수량이 BOM 소요량으로 환산되어 균형을 이루므로,
  //    단순 전체 증감 합계 0 검증이 아니다.
  [ERROR_CODES.UNBALANCED_TRANSACTION]: '거래의 수량 균형이 맞지 않습니다.',
  [ERROR_CODES.MISSING_SOURCE_DOCUMENT]: '원인문서가 필요합니다.',
  [ERROR_CODES.CLOSED_PERIOD_TRANSACTION]: '마감된 기간의 거래는 처리할 수 없습니다.',
  [ERROR_CODES.SKU_NOT_INVENTORY_MANAGED]:
    '재고관리 대상이 아닌 SKU 는 재고 거래에 사용할 수 없습니다.',
  [ERROR_CODES.WAREHOUSE_INACTIVE]: '비활성 창고는 재고 거래에 사용할 수 없습니다.',
  [ERROR_CODES.LOT_REQUIRED_MISSING]: 'LOT 관리 대상 SKU는 LOT 번호가 필요합니다.',
  [ERROR_CODES.LOT_NOT_ALLOWED]: 'LOT 비관리 SKU에는 LOT 번호를 입력할 수 없습니다.',
  [ERROR_CODES.EXPIRY_REQUIRED_MISSING]: '유통기한 관리 대상 SKU는 유통기한이 필요합니다.',
  [ERROR_CODES.EXPIRED_INBOUND]: '만료된 재고는 입고할 수 없습니다.',
  [ERROR_CODES.SERIAL_REQUIRED_MISSING]: '시리얼 관리 대상 SKU는 시리얼 번호가 필요합니다.',
  [ERROR_CODES.SERIAL_QTY_INVALID]: '시리얼 관리 재고의 개별 수량은 ±1이어야 합니다.',
  [ERROR_CODES.SERIAL_NET_QTY_INVALID]: '동일 시리얼의 순수량은 -1부터 1 사이여야 합니다.',
  [ERROR_CODES.SETTING_LOCKED]: '잠긴 설정은 변경할 수 없습니다.',
  [ERROR_CODES.SKU_CODE_IMMUTABLE]: '거래가 발생한 SKU 의 코드는 변경할 수 없습니다.',
  [ERROR_CODES.SKU_ARCHIVE_BLOCKED]: '사용 이력이 있는 SKU 는 폐기할 수 없습니다.',
  [ERROR_CODES.SKU_CODE_DUPLICATE]: '이미 사용 중인 SKU 코드입니다.',
  [ERROR_CODES.SKU_ACTIVE_UPDATE_RESTRICTED]: '활성(ACTIVE) SKU 는 현재 일반 수정이 제한됩니다.',
  [ERROR_CODES.SKU_APPROVAL_VALIDATION_FAILED]: '승인 전 검증을 통과하지 못했습니다.',
  [ERROR_CODES.SKU_CODE_SEQUENCE_EXHAUSTED]:
    '해당 브랜드/대분류/소분류 조합의 SKU 일련번호가 모두 사용되었습니다. 코드 정책 검토가 필요합니다.',
  [ERROR_CODES.BARCODE_SCIENTIFIC_NOTATION]:
    '바코드가 지수표기로 손상되었습니다. 원본 숫자를 문자열로 다시 입력하세요.',
  [ERROR_CODES.BARCODE_UNVERIFIED]: '확인이 필요한 표시값은 바코드로 저장할 수 없습니다.',
  [ERROR_CODES.BARCODE_INVALID_FORMAT]: '바코드는 숫자로만 이루어져야 합니다.',
  [ERROR_CODES.BARCODE_DUPLICATE]: '이미 활성 상태로 사용 중인 바코드입니다.',
  [ERROR_CODES.BARCODE_PRIMARY_CONFLICT]: '이 SKU 에는 이미 활성 대표 바코드가 있습니다.',
  [ERROR_CODES.BARCODE_DUPLICATE_EXCEPTION_NOT_APPLICABLE]:
    '다른 SKU 가 활성으로 사용 중인 바코드가 없어 중복 예외 대상이 아닙니다.',
  [ERROR_CODES.BARCODE_DUPLICATE_CANDIDATE_EXISTS]:
    '내용이 다른 중복 예외 요청이 이미 승인 대기 중입니다.',
  [ERROR_CODES.BARCODE_DUPLICATE_APPROVAL_INVALID_STATE]:
    '중복 예외 승인 대상이 아닌 바코드입니다.',
  [ERROR_CODES.BARCODE_DUPLICATE_APPROVAL_PENDING]:
    '중복 예외 승인 대기 중인 바코드는 일반 수정을 할 수 없습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_CODE_DUPLICATE]:
    '같은 외부시스템에 동일한 외부코드의 현행 매핑이 이미 있습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_CONFLICT]:
    '이 SKU 와 외부시스템 조합에는 이미 대표 매핑이 있습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_IDENTIFIER_REQUIRED]:
    '외부코드·외부바코드·외부상품명 중 최소 하나가 필요합니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_REQUIRES_MATCHED]:
    '외부코드 또는 외부바코드가 있는 매핑만 대표로 지정할 수 있습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_PRIMARY_MUST_BE_CLEARED_BEFORE_END]:
    '대표 매핑을 종료하려면 같은 요청에서 대표를 함께 해제해야 합니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_EFFECTIVE_DATE_INVALID]: '적용 종료일이 올바르지 않습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_ENDED]: '이미 종료된 매핑은 수정할 수 없습니다.',
  [ERROR_CODES.EXTERNAL_MAPPING_UNMATCHED_NOT_INTERACTIVE]:
    'UNMATCHED 매핑은 이 API 로 수정할 수 없습니다.',
  [ERROR_CODES.SUPPLIER_CODE_DUPLICATE]: '이미 사용 중인 거래처 코드입니다.',
  [ERROR_CODES.SUPPLIER_SKU_PERIOD_OVERLAP]:
    '같은 거래처·SKU 에 적용기간이 겹치는 공급조건이 이미 있습니다.',
  [ERROR_CODES.SUPPLIER_SKU_EFFECTIVE_FROM_DUPLICATE]:
    '같은 거래처·SKU 에 동일한 적용 시작일의 공급조건이 이미 있습니다.',
  [ERROR_CODES.SUPPLIER_SKU_PRIMARY_CONFLICT]: '이 SKU 의 현행 우선공급업체가 이미 있습니다.',
  [ERROR_CODES.SUPPLIER_SKU_EFFECTIVE_PERIOD_INVALID]: '공급조건 적용기간이 올바르지 않습니다.',
  [ERROR_CODES.SUPPLIER_SKU_VERSION_DATE_INVALID]: '공급조건 버전 날짜가 올바르지 않습니다.',
  [ERROR_CODES.SUPPLIER_PRICE_EFFECTIVE_FROM_DUPLICATE]:
    '같은 공급조건에 동일한 적용 시작일의 가격이 이미 있습니다.',
  [ERROR_CODES.SUPPLIER_PRICE_UNIT_PRICE_INVALID]: '단가가 올바르지 않습니다.',
  [ERROR_CODES.SUPPLIER_PRICE_CHAIN_CONFLICT]:
    '이 공급조건의 승인 가격 이력이 겹칩니다 — 관리자 확인이 필요합니다.',
  [ERROR_CODES.BOM_NOT_FOUND]: '요청한 BOM 을 찾을 수 없습니다.',
  [ERROR_CODES.BOM_EFFECTIVE_CONFLICT]:
    '이 SKU 의 활성 BOM 이 같은 시점에 둘 이상입니다 — 관리자 확인이 필요합니다.',
  [ERROR_CODES.BOM_SUPPLIER_SELECTION_CONFLICT]:
    '이 구성품의 대표 공급조건이 같은 시점에 둘 이상입니다 — 관리자 확인이 필요합니다.',
  [ERROR_CODES.BOM_CYCLE_DETECTED]: 'BOM 구성이 순환합니다.',
  [ERROR_CODES.BOM_MAX_LEVEL_EXCEEDED]: 'BOM 전개 단계가 허용 깊이를 넘었습니다.',
  [ERROR_CODES.BOM_SELF_COMPONENT]: '상위 SKU 를 자신의 구성품으로 넣을 수 없습니다.',
  [ERROR_CODES.BOM_QTY_INVALID]: '소요량은 0 보다 커야 합니다.',
  [ERROR_CODES.BOM_QTY_STATUS_MISMATCH]: '소요량과 소요량 상태가 맞지 않습니다.',
  [ERROR_CODES.BOM_QTY_UNCONFIRMED]: '소요량이 확정되지 않은 라인이 있습니다.',
  [ERROR_CODES.BOM_UOM_MISMATCH]: '단위가 SKU 기준단위와 다릅니다.',
  [ERROR_CODES.BOM_PARENT_NOT_ELIGIBLE]: '이 SKU 는 BOM 의 상위 품목이 될 수 없습니다.',
  [ERROR_CODES.BOM_COMPONENT_NOT_ELIGIBLE]: '이 SKU 는 구성품으로 사용할 수 없습니다.',
  [ERROR_CODES.BOM_INVALID_TRANSITION]: '현재 상태에서 할 수 없는 작업입니다.',
  [ERROR_CODES.BOM_ACTIVE_IMMUTABLE]: '활성 BOM 은 수정할 수 없습니다. 새 버전을 생성하세요.',
  [ERROR_CODES.BOM_NOT_EDITABLE]: '현재 상태에서는 BOM 을 수정할 수 없습니다.',
  [ERROR_CODES.BOM_VERSION_DUPLICATE]: '같은 상위 SKU 에 동일한 버전이 이미 있습니다.',
  [ERROR_CODES.BOM_PERIOD_OVERLAP]: '같은 상위 SKU 에 적용기간이 겹치는 활성 BOM 이 이미 있습니다.',
  [ERROR_CODES.BOM_LINE_DUPLICATE]: '같은 구성품·대체그룹의 라인이 이미 있습니다.',
  [ERROR_CODES.WAREHOUSE_CODE_DUPLICATE]: '이미 사용 중인 창고 코드입니다.',
  [ERROR_CODES.ENVIRONMENT_ERROR]: '서버 설정 오류가 발생했습니다.',
  [ERROR_CODES.INTERNAL_ERROR]: '요청을 처리하지 못했습니다.',
};

/** 코드에 대응하는 공개 메시지. 알 수 없는 코드는 일반 문구로 대체한다. */
export function publicMessageForCode(code: string): string {
  return PUBLIC_MESSAGE_BY_CODE[code as ErrorCode] ?? PUBLIC_MESSAGE_BY_CODE.INTERNAL_ERROR;
}
